### ISSUE TITLE
Erro ao acessar arquivo anexado em um exercício

### ISSUE THREAD

**Issue by ritomar** [runcodes-icmc/server#7]
Ao acessar um arquivo que está anexado na descrição de um exercício ocorre erro no seaweed:

<img width="659" alt="Captura de Tela 2023-12-01 às 16 16 21" src="https://github.com/runcodes-icmc/server/assets/7781552/6184da54-fb3a-4c4d-87bb-ad4e5bd3fbd8">

**Comment by LiviaLelis** [comment]
Isso costuma ser resultado de um erro de configuração, especificamente na URL assinada pelo código no lado do server não bater com a URL utilizada para o acesso.

Se o problema persistir, sinta-se a vontade para re-abrir esta issue.
